language: python
python:
  - "3.9"
install:
  - make install
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - make build
  - make build.test