version: "3"

services:
  appstore:
    build:
      context: .
      dockerfile: Dockerfile
    image: helxplatform/appstore:context_config-0.1
    volumes:
      - $HOME/.kube/local:/home/appstore/.kube/config
      - $HOME/.minikube/:$HOME/.minikube/
    env_file:
      - .env
    ports:
      - 8000:8000
