# Generated by Django 2.2.10 on 2020-04-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorizedUsers',
            new_name='AuthorizedUser',
        ),
    ]
