# Generated by Django 3.2 on 2023-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200430_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrodAuthorizedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=254)),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
