def secrets = [
    [
        path: 'helx/dev/sterling/helx-dev/appstore', 
        engineVersion: 2, 
        secretValues: [
            [envVar: 'HELM_VALUES', vaultKey: 'values.yaml']
        ]
    ],
]

def configuration = [
    vaultUrl: "$VAULT_ADDR",
    vaultCredentialId: "$VAULT_APP_ROLE", 
    engineVersion: 2
]

pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes'
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: alpine
    workingDir: /home/jenkins/agent
    image: alpine/helm:3.1.1
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "512m"
        memory: "1024Mi"
        ephemeral-storage: "4Gi"
      limits:
        cpu: "1024m"
        memory: "2048Mi"
        ephemeral-storage: "8Gi"
    tty: true
    command:
    - cat
'''
        }
    }
    
    stages {
        stage('Deploy') {
            environment {
                KUBECONFIG = credentials('helx-dev_kubecfg')
                IMAGE_TAG = "${env.IMAGE_TAG}"
            }
            steps {
                container(name: 'alpine', shell: '/bin/ash') {
                    withVault([configuration: configuration, vaultSecrets: secrets]) {
                        sh '''
                            # 1. turn off additional logging
                            set +x

                            # 2. pull values file from vault
                            printf '%s' "$HELM_VALUES" > values.yaml

                            # 3. add image tag to values file
                            cat >> values.yaml <<EOL
                            image:
                              repository: helxplatform/appstore
                              tag: $IMAGE_TAG
                            EOL

                            # 4. turn back on additional logging
                            set -x

                            # 5. configure kubectl
                            helm init --kube-context default-context

                            # 6. run helm install command using values file
                            helm repo add helx-charts https://helxplatform.github.io/helm-charts/
                            helm repo update
                            helm -n helx-dev upgrade --install appstore helx-charts/appstore --values values.yaml
                        '''
                    }
                }
            }
        }
    }
}